### ISSUE TITLE
Limpiar texto antes de anonimizarlo

### ISSUE THREAD

**Issue by mjvallone** [instituciones-abiertas/anonimizacion-texto-libre#22]
en principio habría que cambiar comillas dobles por simples, pero deberíamos hacer una sanitización general

**Comment by cuococarlos** [comment]
Estoy probando con cosas que estan explicitadas en este articulo: 
https://towardsdatascience.com/a-guide-to-cleaning-text-in-python-943356ac86ca

**Comment by cuococarlos** [comment]
Tmb estoy chequeando por aca:
https://dylancastillo.co/nlp-snippets-clean-and-tokenize-text-with-python/

**Comment by mjvallone** [comment]
Hay que tener cuidado cuando se leé desde archivos, tanto en anonimización como en la evaluación de eficiencia; ya que pueden aparecer caracteres raros (por ej: comillas dobles) lo cual podría hacer que no funcione correctamente.
En la anonimización no "sería tan terrible" eliminar esos caracteres, pero en la evaluación de eficiencia SI porque podría afectar a la posición de los tokens (e influir en la comparación que se realiza).
