### ISSUE TITLE
No detecta DRX en texto en mayúsculas

### ISSUE THREAD

**Issue by mjvallone** [instituciones-abiertas/anonimizacion-texto-libre#27]
se probó con el texto --text="INDICO DRA. GONZALEZ"

está la función `find_ent_ocurrencies_in_upper_text` comentada en `model_utils.py`, revisarla para ser usada

**Comment by cuococarlos** [comment]
De este issue se desprenden dos tareas 

- [ ] Actualizar el readme aclarando que es importante para la detección que se encuentre #38 
- [x] Hacer pruebas con la logica de detección de uppercase ya utilizada previamente  para el caso de textos hibridos #37
