### ISSUE TITLE
Crear estructura general de uso

### ISSUE THREAD

**Issue by mjvallone** [instituciones-abiertas/anonimizacion-texto-libre#3]
armar funciones principales y menú que permita su uso mediante consola

**Comment by josx** [comment]
Además del uso mediante consola interactiva que ya está organizado, tenemos que contemplar la siguientes opciones:

- Para Anonimización de documento:
  -  Archivo CSV o Archivo TXT o texto ( ej: --archivo anon.csv o --archivo anon.txt o --txt "esto hay que anon"
  - Si Archivo CSV entonces Nombre de columna o número de columna ( ej: --archivo anon.csv --columna 2 o --archivo anon.csv --columna "txtlibre")

- Para Evaluar eficacia del modelo
   - Lo mismo que para anonimización del documento + etiquetado (ej: --archivo anon.csv --columna 2 --etiquetado etiquetas.txt )

- Para salida de datos
  - Acá se puede usar --output y/o respetar el mismo formato de entrada (si viene con string se podria tirar directamente en el stdout)


> Para --archivo se puede usar --input que usan varios programas

**Comment by mjvallone** [comment]
Asumimos para la anonimización las opciones:
- CSV con una columna a anonimizar 
- texto

**Comment by josx** [comment]
Podes usar [click](https://github.com/pallets/click/) o simil para simplificar el pasaje de argumentos.
